[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-core-skills"
version.workspace = true

[lib]
doctest = false
name = "orbiterx_core_skills"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
orbiterx-analytics = { workspace = true }
orbiterx-config = { workspace = true }
orbiterx-context-fragments = { workspace = true }
orbiterx-exec-server = { workspace = true }
orbiterx-login = { workspace = true }
orbiterx-model-provider = { workspace = true }
orbiterx-otel = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-shell-command = { workspace = true }
orbiterx-skills = { workspace = true }
orbiterx-utils-absolute-path = { workspace = true }
orbiterx-utils-output-truncation = { workspace = true }
orbiterx-utils-path-uri = { workspace = true }
orbiterx-utils-plugins = { workspace = true }
dirs = { workspace = true }
dunce = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt"] }
toml = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
