[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-agent-extension"
version.workspace = true

[lib]
name = "orbiterx_agent_extension"
path = "src/lib.rs"
doctest = false
test = false

[lints]
workspace = true

[dependencies]
orbiterx-core = { workspace = true }
orbiterx-protocol = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
core_test_support = { workspace = true }
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
