[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-prompts"
version.workspace = true

[lib]
doctest = false
name = "orbiterx_prompts"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
orbiterx-context-fragments = { workspace = true }
orbiterx-git-utils = { workspace = true }
orbiterx-execpolicy = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-utils-absolute-path = { workspace = true }
orbiterx-utils-template = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
