packages:
  - orbiterx-standalone
  - frontend
  - orbiterx-cli
  - orbiterx-rs/responses-api-proxy/npm
  - sdk/typescript

ignoredBuiltDependencies: []

minimumReleaseAge: 10080
minimumReleaseAgeExclude: []

blockExoticSubdeps: true
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
trustPolicyExclude: []
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: false
  sharp: true
  unrs-resolver: true
