[package]
name = "orbiterx-process-hardening"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "orbiterx_process_hardening"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
libc = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
