[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
orbiterx-protocol = { workspace = true }
orbiterx-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
