load("//:defs.bzl", "orbiterx_rust_crate")

orbiterx_rust_crate(
    name = "collaboration-mode-templates",
    compile_data = glob(["templates/*.md"]),
    crate_name = "orbiterx_collaboration_mode_templates",
)

exports_files(
    glob(["templates/*.md"]),
    visibility = ["//visibility:public"],
)
