[package]
name = "app_test_support"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
orbiterx-app-server-protocol = { workspace = true }
orbiterx-config = { workspace = true }
orbiterx-core = { workspace = true }
orbiterx-exec-server = { workspace = true }
orbiterx-features = { workspace = true }
orbiterx-login = { workspace = true }
orbiterx-models-manager = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-utils-cargo-bin = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
    "io-util",
    "io-std",
    "macros",
    "net",
    "process",
    "rt-multi-thread",
    "sync",
    "test-util",
    "time",
] }
tokio-util = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
wiremock = { workspace = true }
core_test_support = { path = "../../../core/tests/common" }
shlex = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
