[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-memories-read"
version.workspace = true

[lib]
name = "orbiterx_memories_read"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
orbiterx-protocol = { workspace = true }
orbiterx-shell-command = { workspace = true }
orbiterx-utils-absolute-path = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
