[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-response-debug-context"
version.workspace = true

[lib]
doctest = false
name = "orbiterx_response_debug_context"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
orbiterx-api = { workspace = true }
http = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
