[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-core-api"
version.workspace = true

[lib]
doctest = false
name = "orbiterx_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
orbiterx-app-server-protocol = { workspace = true }
orbiterx-arg0 = { workspace = true }
orbiterx-analytics = { workspace = true }
orbiterx-config = { workspace = true }
orbiterx-core = { workspace = true }
orbiterx-extension-api = { workspace = true }
orbiterx-home = { workspace = true }
orbiterx-image-generation-extension = { workspace = true }
orbiterx-exec-server = { workspace = true }
orbiterx-features = { workspace = true }
orbiterx-login = { workspace = true }
orbiterx-model-provider-info = { workspace = true }
orbiterx-models-manager = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-utils-absolute-path = { workspace = true }
