[package]
name = "core_test_support"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
assert_cmd = { workspace = true }
base64 = { workspace = true }
orbiterx-arg0 = { workspace = true }
orbiterx-config = { workspace = true }
orbiterx-core = { workspace = true }
orbiterx-extension-api = { workspace = true }
orbiterx-exec-server = { workspace = true }
orbiterx-home = { workspace = true }
orbiterx-features = { workspace = true }
orbiterx-hooks = { workspace = true }
orbiterx-login = { workspace = true }
orbiterx-model-provider-info = { workspace = true }
orbiterx-models-manager = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-utils-absolute-path = { workspace = true }
orbiterx-utils-cargo-bin = { workspace = true }
orbiterx-utils-path-uri = { workspace = true }
ctor = { workspace = true }
futures = { workspace = true }
notify = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
regex-lite = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["net", "test-util", "time"] }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true }
wiremock = { workspace = true }
shlex = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
reqwest = { workspace = true }
