[package]
name = "orbiterx-install-context"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "orbiterx_install_context"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
orbiterx-utils-absolute-path = { workspace = true }
orbiterx-utils-home-dir = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
