[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-core-plugins"
version.workspace = true

[lib]
doctest = false
name = "orbiterx_core_plugins"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
orbiterx-analytics = { workspace = true }
orbiterx-app-server-protocol = { workspace = true }
orbiterx-config = { workspace = true }
orbiterx-connectors = { workspace = true }
orbiterx-core-skills = { workspace = true }
orbiterx-exec-server = { workspace = true }
orbiterx-git-utils = { workspace = true }
orbiterx-hooks = { workspace = true }
orbiterx-login = { workspace = true }
orbiterx-mcp = { workspace = true }
orbiterx-model-provider = { workspace = true }
orbiterx-otel = { workspace = true }
orbiterx-plugin = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-tools = { workspace = true }
orbiterx-utils-absolute-path = { workspace = true }
orbiterx-utils-path = { workspace = true }
orbiterx-utils-path-uri = { workspace = true }
orbiterx-utils-plugins = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
flate2 = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt", "time"] }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
zip = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
which = { workspace = true }

[dev-dependencies]
libc = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true, features = ["no-env-filter"] }
wiremock = { workspace = true }
