load("//:defs.bzl", "MACOS_WEBRTC_RUSTC_LINK_FLAGS", "orbiterx_rust_crate")
load("//bazel/platforms:release_binaries.bzl", "multiplatform_binaries")
load("//bazel/rules:e2e_benchmark.bzl", "orbiterx_e2e_benchmark")

orbiterx_rust_crate(
    name = "cli",
    crate_name = "orbiterx_cli",
    extra_binaries = [
        "//orbiterx-rs/bwrap:bwrap",
    ],
    rustc_flags_extra = MACOS_WEBRTC_RUSTC_LINK_FLAGS,
)

multiplatform_binaries(
    name = "orbiterx",
)

orbiterx_e2e_benchmark(
    name = "orbiterx-help",
    binaries = [":orbiterx"],
)
