[package]
name = "orbiterx-chatgpt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
orbiterx-connectors = { workspace = true }
orbiterx-core = { workspace = true }
orbiterx-git-utils = { workspace = true }
orbiterx-login = { workspace = true }
orbiterx-model-provider = { workspace = true }
orbiterx-plugin = { workspace = true }
orbiterx-utils-cli = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
orbiterx-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
