[package]
name = "orbiterx-utils-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true, features = ["derive", "wrap_help"] }
orbiterx-protocol = { workspace = true }
orbiterx-shell-command = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
