[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-tools"
version.workspace = true

[lints]
workspace = true

[dependencies]
orbiterx-code-mode = { workspace = true }
orbiterx-connectors = { workspace = true }
orbiterx-features = { workspace = true }
orbiterx-file-system = { workspace = true }
orbiterx-extension-items = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-utils-absolute-path = { workspace = true }
orbiterx-utils-output-truncation = { workspace = true }
orbiterx-utils-pty = { workspace = true }
orbiterx-utils-string = { workspace = true }
jsonptr = { workspace = true }
rmcp = { workspace = true, default-features = false, features = [
    "base64",
    "macros",
    "schemars",
    "server",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
orbiterx-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
