[package]
edition.workspace = true
license.workspace = true
name = "orbiterx-models-manager"
version.workspace = true

[lib]
doctest = false
name = "orbiterx_models_manager"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
orbiterx-collaboration-mode-templates = { workspace = true }
orbiterx-http-client = { workspace = true }
orbiterx-login = { workspace = true }
orbiterx-otel = { workspace = true }
orbiterx-protocol = { workspace = true }
orbiterx-utils-output-truncation = { workspace = true }
orbiterx-utils-template = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "sync", "time"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
